name = "ethicalcapital-labs"
compatibility_date = "2024-11-07"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "hooks"
id = "caf4e19f1388423fade84340c27a929c"
preview_id = "caf4e19f1388423fade84340c27a929c"
